### PR TITLE
Added .gitignore; BGM Looping now accounts for potential framedrops; Existing BGM loop points corrected to account for the change

### PR DESCRIPTION
**Pull request by potatoTeto**
**Added .gitignore**
Without this file, there is potentially sensitive personal information shared within the .cfg files. I also had it ignore imported asset files, so that the .wav.import/.png.import files wouldn't get cloned to local storage (unsure if this was intentional or not, but I did notice .gitignore missing from the repo in general)

**BGM Looping now accounts for potential framedrops**
To account for potential framedrops, the BGM will loop with a slightly different algorithm. To quote my comments from res://Scenes/Audio/BGMPlayer.gd:

			# Changes to avoid hiccups in audio:
			# Instead of creating a new instance for looped tracks, we seek() the current instance to the new track position.
			# We also don't use loop_start directly: We subtract loop_length (If defined in the bgm_dictionary, it would be: loop_end - loop_start) from get_playback_position() in case any frames got dropped during the calculations
			# Finally, if we are somehow attempting to jump to a negative value, just seek to 0.0

I also went through all of the existing BGMs' loop points, and adjusted all of them to account for the change.

(I have also updated my music from the e-mail to account for this change too: You can find the updated metadata and OGG files on the Google Drive URL, linked in my initial e-mail)

### CODE REVIEW

**Comment by Zortoise** [comment]
Hmm... interesting. I didn't know .gitignore is a thing, I am pretty new to coding.

May I know how did you derive the new loop points? My loop points are taken straight from the .flp files. If it is too time consuming to get the new loop points and if your looping system require such precise loop points, It may be too difficult to implement it...

**Comment by potatoTeto** [comment]
No worries! This can be kind of tricky, and it's a common issue many gamedevs face.

[https://youtu.be/kASnhDrj8So](https://youtu.be/kASnhDrj8So) (Starting from ~2:50 into the video, in [Audacity](https://www.audacityteam.org/)!)

Both the implementation and the looping process are done similar to this video. I'm actually not familiar with the loop point method you mentioned in FL Studio--Is it similar, but done in a different tool (like Edison)? I'm writing my music with FL btw, so I can try the other method!

The code was modified to solve 2 potential issues:

**1. To keep loop points consistent with the framerate that the game runs at**
If the game begins to lag around the time it needs to loop (could even be due to running the game on a lower-spec PC), it may over/undershoot its target: The new code calculates the difference between the time it should have looped, and the position it should update to on the next frame (similar to calculating player movement and checking to avoid overshooting a wall)

**2. To avoid gaps (and overlaps) between two instances emitting BGM**
De-spawning an entity and spawning a new one in its place can create hiccups in the audio, because that takes at least one frame to perform: This can be noticeable when it comes to audio! If done too early, it can create overlapping issues, which can also lead to a muddier mix b/c the song can get twice as loud (fadeout can somewhat resolve the overlap issue, although this would still occur at the peak volume of the fade).

I don't think the method of grabbing loop point values should change with this engine modification, but if it makes for a better workflow, I can use the FL method you mentioned and see if it helps looping the BGM in the current audio engine. Speaking of which: in **TrackLoopTester.exe**, can we get a quick debug key to seek() to about 6-10 seconds before the end of the song? It's definitely a helpful timesaving feature that I was using in the modified source! I left that debug code in this pull request, too: [https://github.com/Zortoise/holoVersus/blob/d9c8ad5f706e0000360f39622d90c0867bb5bd58/Scenes/Audio/BGMPlayer.gd#L32](https://github.com/Zortoise/holoVersus/blob/d9c8ad5f706e0000360f39622d90c0867bb5bd58/Scenes/Audio/BGMPlayer.gd#L32)

**Comment by Zortoise** [comment]
Alright, I will do it later. Got some stuff to do first.

For the FL Studio method... err.. I just look at the Time Display on FL Studio at the start/end of segments.

**Comment by Zortoise** [comment]
Alright, I did some testing.
I think I will stick to my current method, sorry. Although your method does work well with the updated loop points, getting the new loop points is just a lot harder. My old loop points are obtained by reading the Time Display in FL Studio, but they don't work well with your method unfortunately.
Yes, making a new instance each loop may result in hiccups at framedrops, but they are just a lot easier to work with (the loops are designed to overlap each other, so they don't have to be super precise).

I did update the TrackLoopTester.exe with a function that start the track at the last 6 seconds before Loop End, here it is:
https://drive.google.com/file/d/19P758udISC8_vOLjsWE23BCbPY2irdfI

Thanks a lot!

**Comment by potatoTeto** [comment]
Okay, no worries! Regardless, thank you for taking the time to consider the proposal; I will work around the existing workflow (and the updated looping tool will help immensely, too—thank you!

**Pull request closed without merging**
